### ISSUE TITLE
Plugin doesn't work with Deluge 1.3.6

### ISSUE THREAD

**Issue by develop7** [nicklan/Deluge-Pieces-Plugin#7]
Symptoms:
- "Pieces" section in settings doesn't show up
- block colors on "Pieces" tab are reset to default (made my eyes bleed again BTW)
- "Prioritize first pieces" checkbox on torrent properties' "Pieces" tab is effectively ignored

**Comment by Xunie** [comment]
Same problem here.
Platform Win 7 x64 SP1

**Comment by atommixz** [comment]
confirm

**Comment by develop7** [comment]
Can't reproduce
